# Generated by Django 6.1 on 2026-08-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('technology', 'Technology'), ('business', 'Business'), ('arts', 'Arts'), ('food', 'Food'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
